// <auto-generated />
using System;
using Drone.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Drone.Model.Migrations
{
    [DbContext(typeof(DbDroneContext))]
    partial class DbDroneContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Drone.Model.Dron", b =>
                {
                    b.Property<int>("IdDrone")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idDrone");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDrone"));

                    b.Property<int>("CapacidadBateria")
                        .HasColumnType("int")
                        .HasColumnName("capacidadBateria");

                    b.Property<int?>("IdEstado")
                        .HasColumnType("int")
                        .HasColumnName("idEstado");

                    b.Property<int?>("IdModelo")
                        .HasColumnType("int")
                        .HasColumnName("idModelo");

                    b.Property<string>("NumerSerie")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("numerSerie");

                    b.Property<decimal>("PesoLimite")
                        .HasColumnType("decimal(3, 2)")
                        .HasColumnName("pesoLimite");

                    b.HasKey("IdDrone")
                        .HasName("PK__Drone__2CE1B38B031563CC");

                    b.HasIndex("IdEstado");

                    b.HasIndex("IdModelo");

                    b.ToTable("Drone", (string)null);
                });

            modelBuilder.Entity("Drone.Model.Estado", b =>
                {
                    b.Property<int>("IdEstado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idEstado");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEstado"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("descripcion");

                    b.HasKey("IdEstado")
                        .HasName("PK__Estado__62EA894A6169A70C");

                    b.ToTable("Estado", (string)null);
                });

            modelBuilder.Entity("Drone.Model.Medicamento", b =>
                {
                    b.Property<int>("IdMedicamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idMedicamento");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMedicamento"));

                    b.Property<string>("Codigo")
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("codigo");

                    b.Property<int?>("IdDrone")
                        .HasColumnType("int");

                    b.Property<int?>("IdDroneNavigationIdDrone")
                        .HasColumnType("int");

                    b.Property<byte[]>("Imagen")
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("imagen");

                    b.Property<string>("Nombre")
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("nombre");

                    b.Property<decimal>("Peso")
                        .HasColumnType("decimal(3, 2)")
                        .HasColumnName("peso");

                    b.HasKey("IdMedicamento")
                        .HasName("PK__Medicame__42B24C58DDF7C54C");

                    b.HasIndex("IdDroneNavigationIdDrone");

                    b.ToTable("Medicamento", (string)null);
                });

            modelBuilder.Entity("Drone.Model.Modelo", b =>
                {
                    b.Property<int>("IdModelo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idModelo");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdModelo"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("descripcion");

                    b.HasKey("IdModelo")
                        .HasName("PK__Modelo__13A52CD135EA748A");

                    b.ToTable("Modelo", (string)null);
                });

            modelBuilder.Entity("Drone.Model.Dron", b =>
                {
                    b.HasOne("Drone.Model.Estado", "IdEstadoNavigation")
                        .WithMany("Drones")
                        .HasForeignKey("IdEstado")
                        .HasConstraintName("FK__Drone__idEstado__619B8048");

                    b.HasOne("Drone.Model.Modelo", "IdModeloNavigation")
                        .WithMany("Drones")
                        .HasForeignKey("IdModelo")
                        .HasConstraintName("FK__Drone__idModelo__60A75C0F");

                    b.Navigation("IdEstadoNavigation");

                    b.Navigation("IdModeloNavigation");
                });

            modelBuilder.Entity("Drone.Model.Medicamento", b =>
                {
                    b.HasOne("Drone.Model.Dron", "IdDroneNavigation")
                        .WithMany()
                        .HasForeignKey("IdDroneNavigationIdDrone");

                    b.Navigation("IdDroneNavigation");
                });

            modelBuilder.Entity("Drone.Model.Estado", b =>
                {
                    b.Navigation("Drones");
                });

            modelBuilder.Entity("Drone.Model.Modelo", b =>
                {
                    b.Navigation("Drones");
                });
#pragma warning restore 612, 618
        }
    }
}
